# **NumPy: What It Is and Why We Need It**
#### What is NumPy?
NumPy (Numerical Python) is a Python library written in C that provides powerful tools for working with arrays. It allows us to efficiently perform mathematical operations on large datasets, making it an essential library for data science, machine learning, and scientific computing.

#### Why Use NumPy Instead of Regular Python Lists?
You might wonder—why not just use Python lists? The answer is speed and simplicity.

With Python lists, performing mathematical operations like addition or multiplication on every element requires extra work. NumPy makes this effortless:

In [1]:
import numpy as np
import time

In [ ]:
# ❌ Operations on Python Lists (Errors & Limitations)
a = [1, 2, 3] + 2  # ❌ Error: Can’t add a number directly to a list
a = [1, 2, 3] - 2  # ❌ Error: Unsupported operand
a = [1, 2, 3] / 2  # ❌ Error: Unsupported operand
a = [1, 2, 3] * 2  # ✅ Works, but duplicates elements instead of multiplying them
print(a)  # Output: [1, 2, 3, 1, 2, 3] (not what we want)

In [ ]:
# ✅ Operations on NumPy Arrays (Fast & Easy)
a = np.array([1,2,3]) + 2
print(a) # Output: [3 4 5]
a = np.array([1,2,3]) - 2
print(a) # Output: [-1  0  1]
a = np.array([1,2,3]) / 2
print(a) # Output: [0.5 1.  1.5]
a = np.array([1,2,3]) * 2
print(a) # Output: [2 4 6]

#### **NumPy is Faster than Regular Python**
Let’s compare the speed of manual list operations vs. NumPy operations:

In [ ]:
start = time.time()
# Manual multiplication using Python lists
manual_array = [i*2 for i in range(100000)]
print('Manual array took', time.time() - start, 'to complete the array')

# Multiplication using NumPy
start = time.time()
np_array = np.arange(0, 100000) * 2
print('Numpy array took', time.time() - start, 'to complete the array')

#### **Creating NumPy Arrays**

In [ ]:
a = np.array([1,2,3])
print("1 dimensional array",a)
# b = np.array([1,2,3], [4,5,6]) this will give an error as np.array() requires a single array of inputs
# corect way to generate multi-dimensional array
b = np.array([[1,2,3],[4,5,6]])
print("2 dimensional array",b)
b = np.array([[1,2,3],[4,5,6], [7,8,9]])
print("3 dimensional array",b)

#### **NumPy provides several convenient ways to create different types of arrays:**

In [ ]:
np_zeros = np.zeros((3,4))
np_ones = np.ones((3,4))
np_random = np.random.random((3,4))
np_constants = np.full((3,4), 2)
np_sequence = np.arange(0, 11, 2)
print(np_zeros)
print(np_ones)
print(np_random)
print(np_constants)
print(np_sequence)

### Vectors, Matrices and Tensors
Vectors: a 1D array representing a collection of numbers typically used for positions, velocities or features

Matrices: a 2D array used for linear algebra, transformation and solving equations

Tensors: a multi-dimensional array(3D or higher)

In [ ]:
vectors = np.array([1,2,3])
matrix = np.array([[1,2,3],[4,5,6]])
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(vectors)
print(matrix)
print(tensor)

#### **Properties of array**

In [ ]:
array = np.array([1,2,3])
print(array.shape) # (3,) -> Number of elements in each dimension
print(array.ndim) # 1 -> Number of dimensions
print(array.size) # 3 -> Total elements in array
print(array.dtype) # int64

#### **Reshaping Arrays**

In [ ]:
array = np.array([1,2,3,4])
reshaped_array = array.reshape((2,2)) # Reshape into 2x2 matrix
flattened_array = reshaped_array.flatten() # Converts a multi-dimensional array into 1D. Always returns a copy
raveled_array = reshaped_array.ravel() # returns a view of the original array(does not allocate new memory). If view is not possible then returns a copy
transposed_array = reshaped_array.T # swap rows and colum
print(reshaped_array)
raveled_array[0] = 5 # this will affect the original reshaped_array
print(reshaped_array)
print(raveled_array)
print(flattened_array)
print(transposed_array)

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0, 2])

#### **Slicing, Sorting, Filtering and Masking**
NumPy allows you to easily access specific parts of an array using slicing, sorting, filtering, and masking. These operations make it easier to work with data efficiently.

In [ ]:
np_array = np.array([
    [1, 5, 6],
    [4, 8, 9],
    [7, 2, 4]
])
# Accessing a single element using two different ways
print(np_array[0, 1])  # 5 (Row 0, Column 1)
print(np_array[0][1])  # Same as above

print(np_array[2, 2])  # 4 (Row 2, Column 2)
print(np_array[2][2])  # Same as above

# Extracting a full row
print(np_array[0, :])  # [1, 5, 6] (First row)
print(np_array[0])     # Same as above

# Extracting a full column
print(np_array[:, 2])  # [6, 9, 4] (Third column)

# Sort each column individually
print(np.sort(np_array, axis=0))
# Output:
# [[1 2 4]
#  [4 5 6]
#  [7 8 9]]

# Sort each row individually
print(np.sort(np_array, axis=1))
# Output:
# [[1 5 6]
#  [4 8 9]
#  [2 4 7]]

np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Extract even numbers
print(np_array[np_array % 2 == 0])  # Output: [2 4 6 8]

# Masking: Create a boolean array where condition (value > 5) is True
mask = np_array > 5
print(np_array[mask])  # Output: [6 7 8 9]

# Divide even numbers by 2, keep odd numbers unchanged
conditional_array = np.where(np_array % 2 == 0, np_array / 2, np_array)
# np.where(condition, operation, else caluse), wherever the condition is true the operation gets executed otherwise the else clause gets executed
# original array [1,2,3,4,5,6,7,8,9], condition = array % 2 == 0(values which are even), operation = divide the values by 2, else add the original value
print(conditional_array)
# Output: [1. 1. 3. 2. 5. 3. 7. 4. 9.]

# Replace numbers greater than 5 with the string "true", else "false"
conditional_array2 = np.where(np_array > 5, 'true', 'false')
# where the condition of value > 5 is true in the array [1,2,3,4,5,6,7,8,9], the string 'true' is added otherwise 'false' is added
print(conditional_array2)
# Output: ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true']


#### **Adding and Deleting rows and columns**

In [4]:
np_array1 = np.array([1, 2, 3])
np_array2 = np.array([4, 5, 6])

# Merging two 1D arrays
concatenated_array = np.concatenate((np_array1, np_array2))
print(concatenated_array)  
# Output: [1 2 3 4 5 6]

# Adding a new row
new_row = np.array([7, 8, 9])
with_new_row = np.vstack((np_array1, new_row))
print(with_new_row)
# Output:
# [[1 2 3]
#  [7 8 9]]

# Adding a new column
new_column = np.array([[4], [10]])  # Each value must be in a separate list
with_new_column = np.hstack((with_new_row, new_column))
print(with_new_column)
# Output:
# [[ 1  2  3  4]
#  [ 7  8  9 10]]

# deleting
deleted_array = np.delete(with_new_column, 3, axis=1) # (target array, index, axis(0 for row, 1 for column))
print(deleted_array)
# Output:
# [[1 2 3]
#  [7 8 9]]

[1 2 3 4 5 6]
[[1 2 3]
 [7 8 9]]
[[ 1  2  3  4]
 [ 7  8  9 10]]
[[1 2 3]
 [7 8 9]]
